name: Private Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        if: github.actor == 'username' && github.event_name == 'push'
        run: |
          # مراحل لازم برای ساخت و انتشار
          echo "Hello, this is a private workflow for user 'username'."
